//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adherent
    {
        public int idMembre { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> DateDeNaissance { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Email { get; set; }
        public int idNiveau { get; set; }
    
        public virtual Niveau Niveau { get; set; }
    }
}
