//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrainement
    {
        public int idEntrainement { get; set; }
        public Nullable<System.DateTime> DateEntrainement { get; set; }
        public Nullable<System.TimeSpan> HeureDebut { get; set; }
        public Nullable<System.TimeSpan> HeureFin { get; set; }
        public int idEntrainement_1 { get; set; }
        public int idEntraineur { get; set; }
        public int idEquipe { get; set; }
    
        public virtual TypeEntrainement TypeEntrainement { get; set; }
        public virtual Entraineur Entraineur { get; set; }
        public virtual Equipe Equipe { get; set; }
    }
}
