//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int idMatch { get; set; }
        public string Libelle { get; set; }
        public Nullable<System.DateTime> DateMatch { get; set; }
        public string Resultat { get; set; }
        public int idEquipe { get; set; }
    
        public virtual Equipe Equipe { get; set; }
    }
}
