//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Boehler_FootEntities : DbContext
    {
        public Boehler_FootEntities()
            : base("name=Boehler_FootEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adherent> Adherents { get; set; }
        public virtual DbSet<Entrainement> Entrainements { get; set; }
        public virtual DbSet<Entraineur> Entraineurs { get; set; }
        public virtual DbSet<Equipe> Equipes { get; set; }
        public virtual DbSet<Match> Matchs { get; set; }
        public virtual DbSet<Niveau> Niveaux { get; set; }
        public virtual DbSet<TypeEntrainement> TypeEntrainements { get; set; }
    }
}
